inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - Gemfile

Documentation:
  Enabled: false
